<?php 

$productList =
array (
    array('nome' => 'edgard Cooper',
            'prezzo' => '80 $',
            'logo'=> 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQovdvZcVmUCGv7zMIE-D8mQL4hnQhFl9cF78G7L3xp2EP-dXWQTf96-b5VskWsmY3NprpvUKXo_YkO4KHJPqrVC1_8-8wWxgD9-fYbsgszSx8JKTg2gdqU2w&usqp=CAE', 
            'tipologia' => 'cibo', 
            'categoria' => 'cane',
            'calorie' => '500 calorie',
            'taglia' => 'taglia grande'
         ),
    array('nome' => 'one',
            'prezzo' => '3 $',
            'logo'=> 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQovdvZcVmUCGv7zMIE-D8mQL4hnQhFl9cF78G7L3xp2EP-dXWQTf96-b5VskWsmY3NprpvUKXo_YkO4KHJPqrVC1_8-8wWxgD9-fYbsgszSx8JKTg2gdqU2w&usqp=CAE', 
            'tipologia' => 'cibo', 
            'categoria' => 'gatto',
            'calorie' => '200 calorie',
            'taglia' => 'taglia piccola',
        ),
    array('nome' => 'Cooper',
            'prezzo' => '40 $',
            'logo'=> 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQovdvZcVmUCGv7zMIE-D8mQL4hnQhFl9cF78G7L3xp2EP-dXWQTf96-b5VskWsmY3NprpvUKXo_YkO4KHJPqrVC1_8-8wWxgD9-fYbsgszSx8JKTg2gdqU2w&usqp=CAE', 
            'tipologia' => 'cuccia', 
            'categoria' => 'cane',
            'larghezza' => 'Larghezza: 120cm',
            'altezza' => 'altezza: 120cm'),
    array('nome' => 'Pallina',
            'prezzo' => '110 $',
            'logo'=> 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQovdvZcVmUCGv7zMIE-D8mQL4hnQhFl9cF78G7L3xp2EP-dXWQTf96-b5VskWsmY3NprpvUKXo_YkO4KHJPqrVC1_8-8wWxgD9-fYbsgszSx8JKTg2gdqU2w&usqp=CAE', 
            'tipologia' => 'giochi', 
            'categoria' => 'cane',
            'materiale' => 'Materiale: plastica',
            'rumoroso' => 'Rumoroso: si'),
    array('nome' => 'Coo',
            'prezzo' => '43 $',
            'logo'=> 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQovdvZcVmUCGv7zMIE-D8mQL4hnQhFl9cF78G7L3xp2EP-dXWQTf96-b5VskWsmY3NprpvUKXo_YkO4KHJPqrVC1_8-8wWxgD9-fYbsgszSx8JKTg2gdqU2w&usqp=CAE', 
            'tipologia' => 'cibo', 
            'categoria' => 'cane',
            'calorie' => '300 calorie',
            'taglia' => ' taglia: media',),
    array('nome' => 'edgard',
            'prezzo' => '200 $',
            'logo'=> 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQovdvZcVmUCGv7zMIE-D8mQL4hnQhFl9cF78G7L3xp2EP-dXWQTf96-b5VskWsmY3NprpvUKXo_YkO4KHJPqrVC1_8-8wWxgD9-fYbsgszSx8JKTg2gdqU2w&usqp=CAE', 
            'tipologia' => 'cuccia', 
            'categoria' => 'cane',
            'larghezza' => 'Larghezza: 200cm',
            'altezza' => 'Altezza: 200cm'),
    array('nome' => 'Cooper',
            'prezzo' => '30 $',
            'logo'=> 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQovdvZcVmUCGv7zMIE-D8mQL4hnQhFl9cF78G7L3xp2EP-dXWQTf96-b5VskWsmY3NprpvUKXo_YkO4KHJPqrVC1_8-8wWxgD9-fYbsgszSx8JKTg2gdqU2w&usqp=CAE', 
            'tipologia' => 'giochi', 
            'categoria' => 'cane',
            'materiale' => 'Materiale: legno',
            'rumoroso' => 'Rumoroso: no'),
   );

?>