<?php 

$productList =
array (
    array('nome' => 'edgard Cooper',
            'prezzo' => 80,
            'logo'=> '', 
            'tipologia' => 'cibo', 
            'categoria' => 'cane',
            'calorie' => 500,
            'taglia' => 'grande'
         ),
    array('nome' => 'one',
            'prezzo' => 3,
            'logo'=> '', 
            'tipologia' => 'cibo', 
            'categoria' => 'gatto',
            'calorie' => 200,
            'taglia' => 'piccolo',
        ),
    array('nome' => 'edgard Cooper',
            'prezzo' => 80,
            'logo'=> '', 
            'tipologia' => 'cuccia', 
            'categoria' => 'cane',
            'larghezza' => '120cm',
            'altezza' => '120cm'),
    array('nome' => 'edgard Cooper',
            'prezzo' => 80,
            'logo'=> '', 
            'tipologia' => 'giochi', 
            'categoria' => 'cane',
            'materiale' => 'plastica',
            'rumoroso' => true),
    array('nome' => 'edgard Cooper',
            'prezzo' => 80,
            'logo'=> '', 
            'tipologia' => 'cibo', 
            'categoria' => 'cane',
            'calorie' => 300,
            'taglia' => 'medio',),
    array('nome' => 'edgard Cooper',
            'prezzo' => 80,
            'logo'=> '', 
            'tipologia' => 'cuccia', 
            'categoria' => 'cane',
            'larghezza' => '200cm',
            'altezza' => '200cm'),
    array('nome' => 'edgard Cooper',
            'prezzo' => 80,
            'logo'=> '', 
            'tipologia' => 'giochi', 
            'categoria' => 'cane',
            'materiale' => 'legno',
            'rumoroso' => false),
   );

?>